"""add_sensor_readings_table

Revision ID: 0f8f38fe3f92
Revises: e1f2a3b4c5d6
Create Date: 2026-03-04 10:58:36.519551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f8f38fe3f92'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # sensor_readings jadvali Master_Schema da yo'q — bu yerda yaratamiz
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='sensor_readings')"
    ))
    table_exists = result.scalar()

    if not table_exists:
        op.create_table(
            'sensor_readings',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('animal_id', sa.Integer(), nullable=False),
            sa.Column('device_id', sa.String(length=100), nullable=True),
            sa.Column('sensor_type', sa.String(length=50), nullable=False, server_default='ambient_temperature'),
            sa.Column('value', sa.Float(), nullable=False, server_default='0'),
            sa.Column('unit', sa.String(length=20), nullable=False, server_default=''),
            sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
            sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
            sa.Column('is_anomaly', sa.Boolean(), nullable=False, server_default=sa.text('false')),
            sa.Column('quality_score', sa.Float(), nullable=False, server_default=sa.text("'1'")),
            sa.Column('anomaly_reason', sa.String(length=500), nullable=True),
            sa.Column('source', sa.String(length=20), nullable=False, server_default='iot_device'),
            sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name='sensor_readings_animal_id_fkey', ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index('ix_sensor_readings_sensor_type', 'sensor_readings', ['sensor_type'], unique=False)
        op.create_index('ix_sensor_readings_measured_at', 'sensor_readings', ['measured_at'], unique=False)
        op.create_index('ix_sensor_readings_is_anomaly', 'sensor_readings', ['is_anomaly'], unique=False)
        op.create_index('ix_sensor_readings_anomaly_measured', 'sensor_readings', ['is_anomaly', 'measured_at'], unique=False)
        op.create_index('ix_sensor_readings_animal_type_measured', 'sensor_readings', ['animal_id', 'sensor_type', 'measured_at'], unique=False)
        op.create_index('ix_sensor_readings_animal_measured_at', 'sensor_readings', ['animal_id', 'measured_at'], unique=False)

    op.drop_index('ix_training_runs_created_at', table_name='training_runs')
    op.drop_index('ix_training_runs_is_deployed', table_name='training_runs')
    op.drop_index('ix_training_runs_status', table_name='training_runs')
    op.drop_table('training_runs')
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.VARCHAR(length=64),
               comment='AuditEventType qiymati',
               existing_nullable=False)
    op.alter_column('audit_logs', 'severity',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               comment='info / warning / critical',
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Harakat qilgan foydalanuvchi ID (nullable)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'username',
               existing_type=sa.VARCHAR(length=64),
               comment="Foydalanuvchi nomi — user o'chirilsa ham saqlansin",
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment="So'rov yuborgan IP manzili",
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=512),
               comment='Brauzer / klient User-Agent',
               existing_nullable=True)
    op.alter_column('audit_logs', 'endpoint',
               existing_type=sa.VARCHAR(length=256),
               comment="HTTP so'rov yo'li",
               existing_nullable=True)
    op.alter_column('audit_logs', 'http_method',
               existing_type=sa.VARCHAR(length=8),
               comment='HTTP metod: GET, POST, ...',
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="Qo'shimcha kontekst (JSON)",
               existing_nullable=True)
    op.alter_column('audit_logs', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Voqea UTC vaqti',
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               comment='Primary key',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('cameras', 'camera_id',
               existing_type=sa.VARCHAR(length=64),
               comment='Noyob kamera identifikatori, masalan: CAM-BARN-01',
               existing_nullable=False)
    op.alter_column('cameras', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment="Ko'rsatiladigan nom, masalan: Shimoliy molxona",
               existing_nullable=False)
    op.alter_column('cameras', 'type',
               existing_type=postgresql.ENUM('simulated', 'usb', 'rtsp', name='camera_type'),
               type_=sa.Enum('simulated', 'usb', 'rtsp', name='camera_type', native_enum=False),
               comment='Kamera manba turi: simulated | usb | rtsp',
               existing_nullable=False)
    op.alter_column('cameras', 'source',
               existing_type=sa.VARCHAR(length=512),
               comment='RTSP URL (masalan: rtsp://192.168.1.100:554/stream) yoki None',
               existing_nullable=True)
    op.alter_column('cameras', 'device_index',
               existing_type=sa.INTEGER(),
               comment='USB kamera indeks raqami (0 — birinchi kamera)',
               existing_nullable=True)
    op.alter_column('cameras', 'fps',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Maqsadli kadr tezligi (FPS). Tavsiya: 10–15',
               existing_nullable=False)
    op.alter_column('cameras', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment="False = kamera o'chirilgan (o'chirilmaydi, faqat deaktiv)",
               existing_nullable=False)
    op.alter_column('cameras', 'id',
               existing_type=sa.INTEGER(),
               comment='Primary key',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('cameras', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cameras', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_cameras_camera_id', 'cameras', type_='unique')
    op.create_index(op.f('ix_cameras_camera_id'), 'cameras', ['camera_id'], unique=True)
    op.alter_column('health_predictions', 'prediction_date',
               existing_type=sa.VARCHAR(length=10),
               comment='Date of prediction, ISO format YYYY-MM-DD',
               existing_comment='Bashorat sanasi ISO format YYYY-MM-DD',
               existing_nullable=False)
    op.alter_column('health_predictions', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_comment='Model confidence (0.0 — 1.0). Low when insufficient data.',
               existing_nullable=False)
    op.alter_column('health_predictions', 'rule_risk',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_comment='Rule-based component risk (0 — 100)',
               existing_nullable=False)
    op.alter_column('health_predictions', 'rf_risk',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_comment='RandomForest component risk (0 — 100)',
               existing_nullable=False)
    op.alter_column('health_predictions', 'isolation_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_comment='IsolationForest anomaly score converted to risk (0 — 100)',
               existing_nullable=False)
    op.alter_column('health_predictions', 'adi_days_available',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_comment='Number of ADI records used in computation',
               existing_nullable=False)
    op.alter_column('health_predictions', 'features_used',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_comment='Total feature count fed to the model',
               existing_nullable=False)
    op.alter_column('health_predictions', 'model_version',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='Model version that produced this prediction',
               existing_nullable=False)
    op.alter_column('health_predictions', 'raw_features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Raw feature vector used for debugging and retraining',
               existing_comment='Raw feature vector for debugging and retraining',
               existing_nullable=True)
    op.alter_column('health_predictions', 'id',
               existing_type=sa.INTEGER(),
               comment='Primary key',
               existing_comment='Internal surrogate key',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('health_predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was created',
               existing_comment='Yozuv yaratilgan vaqt',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('health_predictions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was last updated',
               existing_comment='Yozuv yangilangan vaqt',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('sensor_readings', sa.Column('device_type', sa.String(length=50), nullable=False, comment='Qurilma turi: collar | scale | camera | environment'))
    op.add_column('sensor_readings', sa.Column('temperature', sa.Float(), nullable=True, comment='Tana harorati °C'))
    op.add_column('sensor_readings', sa.Column('heart_rate', sa.Float(), nullable=True, comment='Yurak urishi bpm'))
    op.add_column('sensor_readings', sa.Column('activity_level', sa.Float(), nullable=True, comment='Faollik 0.0-1.0'))
    op.add_column('sensor_readings', sa.Column('weight_kg', sa.Float(), nullable=True, comment='Vazn kg'))
    op.add_column('sensor_readings', sa.Column('recorded_at', sa.DateTime(), nullable=False, comment="O'lchov vaqti (UTC)"))
    op.alter_column('sensor_readings', 'animal_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment="Jonivor ID (agar aniq bog'langan bo'lsa)")
    op.alter_column('sensor_readings', 'device_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment='Sensor qurilma ID (masalan: collar-001, scale-A)')
    op.alter_column('sensor_readings', 'id',
               existing_type=sa.INTEGER(),
               comment='Primary key',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sensor_readings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sensor_readings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_sensor_readings_animal_measured_at', table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_animal_type_measured', table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_anomaly_measured', table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_is_anomaly', table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_measured_at', table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_sensor_type', table_name='sensor_readings')
    op.create_index('ix_sensor_animal_time', 'sensor_readings', ['animal_id', 'recorded_at'], unique=False)
    op.create_index('ix_sensor_device_time', 'sensor_readings', ['device_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_device_id'), 'sensor_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    op.drop_constraint('sensor_readings_animal_id_fkey', 'sensor_readings', type_='foreignkey')
    op.create_foreign_key(None, 'sensor_readings', 'animals', ['animal_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sensor_readings', 'unit')
    op.drop_column('sensor_readings', 'measured_at')
    op.drop_column('sensor_readings', 'raw_data')
    op.drop_column('sensor_readings', 'value')
    op.drop_column('sensor_readings', 'is_anomaly')
    op.drop_column('sensor_readings', 'sensor_type')
    op.drop_column('sensor_readings', 'quality_score')
    op.drop_column('sensor_readings', 'anomaly_reason')
    op.drop_column('sensor_readings', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('source', postgresql.ENUM('iot_device', 'manual', 'api', name='sensor_source_enum'), server_default=sa.text("'iot_device'::sensor_source_enum"), autoincrement=False, nullable=False))
    op.add_column('sensor_readings', sa.Column('anomaly_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('sensor_readings', sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=False))
    op.add_column('sensor_readings', sa.Column('sensor_type', postgresql.ENUM('body_temperature', 'heart_rate', 'respiratory_rate', 'ambient_temperature', 'humidity', 'activity_level', name='sensor_type_enum'), autoincrement=False, nullable=False))
    op.add_column('sensor_readings', sa.Column('is_anomaly', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('sensor_readings', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sensor_readings', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('sensor_readings', sa.Column('measured_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('sensor_readings', sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sensor_readings', type_='foreignkey')
    op.create_foreign_key('sensor_readings_animal_id_fkey', 'sensor_readings', 'animals', ['animal_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_device_id'), table_name='sensor_readings')
    op.drop_index('ix_sensor_device_time', table_name='sensor_readings')
    op.drop_index('ix_sensor_animal_time', table_name='sensor_readings')
    op.create_index('ix_sensor_readings_sensor_type', 'sensor_readings', ['sensor_type'], unique=False)
    op.create_index('ix_sensor_readings_measured_at', 'sensor_readings', ['measured_at'], unique=False)
    op.create_index('ix_sensor_readings_is_anomaly', 'sensor_readings', ['is_anomaly'], unique=False)
    op.create_index('ix_sensor_readings_anomaly_measured', 'sensor_readings', ['is_anomaly', 'measured_at'], unique=False)
    op.create_index('ix_sensor_readings_animal_type_measured', 'sensor_readings', ['animal_id', 'sensor_type', 'measured_at'], unique=False)
    op.create_index('ix_sensor_readings_animal_measured_at', 'sensor_readings', ['animal_id', 'measured_at'], unique=False)
    op.alter_column('sensor_readings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sensor_readings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sensor_readings', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sensor_readings', 'device_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment=None,
               existing_comment='Sensor qurilma ID (masalan: collar-001, scale-A)')
    op.alter_column('sensor_readings', 'animal_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment="Jonivor ID (agar aniq bog'langan bo'lsa)")
    op.drop_column('sensor_readings', 'recorded_at')
    op.drop_column('sensor_readings', 'weight_kg')
    op.drop_column('sensor_readings', 'activity_level')
    op.drop_column('sensor_readings', 'heart_rate')
    op.drop_column('sensor_readings', 'temperature')
    op.drop_column('sensor_readings', 'device_type')
    op.alter_column('health_predictions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Yozuv yangilangan vaqt',
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('health_predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Yozuv yaratilgan vaqt',
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('health_predictions', 'id',
               existing_type=sa.INTEGER(),
               comment='Internal surrogate key',
               existing_comment='Primary key',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('health_predictions', 'raw_features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Raw feature vector for debugging and retraining',
               existing_comment='Raw feature vector used for debugging and retraining',
               existing_nullable=True)
    op.alter_column('health_predictions', 'model_version',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'v1.0-ensemble'::character varying"),
               existing_comment='Model version that produced this prediction',
               existing_nullable=False)
    op.alter_column('health_predictions', 'features_used',
               existing_type=sa.SMALLINT(),
               server_default=sa.text("'0'::smallint"),
               existing_comment='Total feature count fed to the model',
               existing_nullable=False)
    op.alter_column('health_predictions', 'adi_days_available',
               existing_type=sa.SMALLINT(),
               server_default=sa.text("'0'::smallint"),
               existing_comment='Number of ADI records used in computation',
               existing_nullable=False)
    op.alter_column('health_predictions', 'isolation_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_comment='IsolationForest anomaly score converted to risk (0 — 100)',
               existing_nullable=False)
    op.alter_column('health_predictions', 'rf_risk',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_comment='RandomForest component risk (0 — 100)',
               existing_nullable=False)
    op.alter_column('health_predictions', 'rule_risk',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_comment='Rule-based component risk (0 — 100)',
               existing_nullable=False)
    op.alter_column('health_predictions', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.5'::double precision"),
               existing_comment='Model confidence (0.0 — 1.0). Low when insufficient data.',
               existing_nullable=False)
    op.alter_column('health_predictions', 'prediction_date',
               existing_type=sa.VARCHAR(length=10),
               comment='Bashorat sanasi ISO format YYYY-MM-DD',
               existing_comment='Date of prediction, ISO format YYYY-MM-DD',
               existing_nullable=False)
    op.drop_index(op.f('ix_cameras_camera_id'), table_name='cameras')
    op.create_unique_constraint('uq_cameras_camera_id', 'cameras', ['camera_id'])
    op.alter_column('cameras', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cameras', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cameras', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('cameras', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment="False = kamera o'chirilgan (o'chirilmaydi, faqat deaktiv)",
               existing_nullable=False)
    op.alter_column('cameras', 'fps',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               comment=None,
               existing_comment='Maqsadli kadr tezligi (FPS). Tavsiya: 10–15',
               existing_nullable=False)
    op.alter_column('cameras', 'device_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='USB kamera indeks raqami (0 — birinchi kamera)',
               existing_nullable=True)
    op.alter_column('cameras', 'source',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='RTSP URL (masalan: rtsp://192.168.1.100:554/stream) yoki None',
               existing_nullable=True)
    op.alter_column('cameras', 'type',
               existing_type=sa.Enum('simulated', 'usb', 'rtsp', name='camera_type', native_enum=False),
               type_=postgresql.ENUM('simulated', 'usb', 'rtsp', name='camera_type'),
               comment=None,
               existing_comment='Kamera manba turi: simulated | usb | rtsp',
               existing_nullable=False)
    op.alter_column('cameras', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Ko'rsatiladigan nom, masalan: Shimoliy molxona",
               existing_nullable=False)
    op.alter_column('cameras', 'camera_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Noyob kamera identifikatori, masalan: CAM-BARN-01',
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.alter_column('audit_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Voqea UTC vaqti',
               existing_nullable=False)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment="Qo'shimcha kontekst (JSON)",
               existing_nullable=True)
    op.alter_column('audit_logs', 'http_method',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='HTTP metod: GET, POST, ...',
               existing_nullable=True)
    op.alter_column('audit_logs', 'endpoint',
               existing_type=sa.VARCHAR(length=256),
               comment=None,
               existing_comment="HTTP so'rov yo'li",
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Brauzer / klient User-Agent',
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment="So'rov yuborgan IP manzili",
               existing_nullable=False)
    op.alter_column('audit_logs', 'username',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment="Foydalanuvchi nomi — user o'chirilsa ham saqlansin",
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Harakat qilgan foydalanuvchi ID (nullable)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'severity',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'info'::character varying"),
               comment=None,
               existing_comment='info / warning / critical',
               existing_nullable=False)
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='AuditEventType qiymati',
               existing_nullable=False)
    op.create_table('training_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Internal surrogate key'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record last update timestamp'),
    sa.Column('run_name', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False, comment='Human-readable run name'),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False, comment='pending|collecting|building|training|evaluating|completed|failed|deployed'),
    sa.Column('base_model_name', sa.VARCHAR(length=100), server_default=sa.text("'yolo11n.pt'::character varying"), autoincrement=False, nullable=False, comment='Base model filename'),
    sa.Column('epochs', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=False, comment='Training epochs'),
    sa.Column('batch_size', sa.INTEGER(), server_default=sa.text('8'), autoincrement=False, nullable=False, comment='Batch size'),
    sa.Column('img_size', sa.INTEGER(), server_default=sa.text('640'), autoincrement=False, nullable=False, comment='Input image size'),
    sa.Column('freeze_layers', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False, comment='Number of frozen backbone layers'),
    sa.Column('dataset_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Dataset statistics JSON'),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Training start time'),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Training completion time'),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Training metrics JSON'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='Error message if failed'),
    sa.Column('model_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Saved model file path'),
    sa.Column('is_deployed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment="True if this run's model is currently active"),
    sa.Column('deployed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Deployment timestamp'),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='User notes'),
    sa.PrimaryKeyConstraint('id', name='training_runs_pkey')
    )
    op.create_index('ix_training_runs_status', 'training_runs', ['status'], unique=False)
    op.create_index('ix_training_runs_is_deployed', 'training_runs', ['is_deployed'], unique=False)
    op.create_index('ix_training_runs_created_at', 'training_runs', ['created_at'], unique=False)
    # ### end Alembic commands ###