"""Add WeightMeasurement model with time-series indexes

Revision ID: 18d7c3a397a0
Revises: d13ce7624196
Create Date: 2026-02-10 23:22:03.804016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d7c3a397a0'
down_revision: Union[str, None] = 'd13ce7624196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_measurements',
    sa.Column('animal_id', sa.Integer(), nullable=False, comment='Reference to the animal being measured'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='When the measurement was captured (camera timestamp)'),
    sa.Column('estimated_weight_kg', sa.Float(), nullable=False, comment='AI-estimated weight in kilograms'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='AI model confidence score (0.0 to 1.0)'),
    sa.Column('camera_id', sa.String(length=50), nullable=False, comment='Identifier of the camera that captured this measurement'),
    sa.Column('raw_ai_data', sa.JSON(), nullable=True, comment='\n        Raw AI model output stored as JSONB. May include:\n        - bounding_box: {x, y, width, height}\n        - segmentation_mask: compressed polygon coordinates\n        - feature_vector: embedding from neural network\n        - model_version: version of the AI model used\n        - processing_time_ms: inference latency\n        \n        This data is crucial for:\n        1. Model retraining (ground truth comparison)\n        2. Debugging incorrect predictions\n        3. A/B testing different model versions\n        4. Performance monitoring\n        '),
    sa.Column('image_path', sa.String(length=500), nullable=True, comment='Path to stored image frame (if enabled)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='check_confidence_range'),
    sa.CheckConstraint('estimated_weight_kg > 0', name='check_weight_positive'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_measurements_animal_id'), 'weight_measurements', ['animal_id'], unique=False)
    op.create_index('ix_weight_measurements_animal_time', 'weight_measurements', ['animal_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_weight_measurements_camera_id'), 'weight_measurements', ['camera_id'], unique=False)
    op.create_index('ix_weight_measurements_camera_time', 'weight_measurements', ['camera_id', 'timestamp'], unique=False)
    op.create_index('ix_weight_measurements_confidence', 'weight_measurements', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_weight_measurements_confidence_score'), 'weight_measurements', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_weight_measurements_timestamp'), 'weight_measurements', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_measurements_timestamp'), table_name='weight_measurements')
    op.drop_index(op.f('ix_weight_measurements_confidence_score'), table_name='weight_measurements')
    op.drop_index('ix_weight_measurements_confidence', table_name='weight_measurements')
    op.drop_index('ix_weight_measurements_camera_time', table_name='weight_measurements')
    op.drop_index(op.f('ix_weight_measurements_camera_id'), table_name='weight_measurements')
    op.drop_index('ix_weight_measurements_animal_time', table_name='weight_measurements')
    op.drop_index(op.f('ix_weight_measurements_animal_id'), table_name='weight_measurements')
    op.drop_table('weight_measurements')
    # ### end Alembic commands ###
