"""Master_Schema

Revision ID: 50e524a6cb38
Revises: 
Create Date: 2026-02-20 11:25:48.618590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e524a6cb38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('tag_id', sa.String(length=50), nullable=False, comment='Unique tag identifier (e.g., JNV-001)'),
    sa.Column('species', sa.Enum('CATTLE', 'SHEEP', 'GOAT', 'HORSE', 'OTHER', name='animal_species'), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='animal_gender'), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True, comment='Date of birth (if known)'),
    sa.Column('acquisition_date', sa.DateTime(), nullable=False, comment='Date when animal was acquired'),
    sa.Column('status', sa.Enum('ACTIVE', 'QUARANTINE', 'SICK', 'SOLD', 'DECEASED', 'TRANSFERRED', name='animal_status'), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(), nullable=True),
    sa.Column('last_detected_at', sa.DateTime(), nullable=True),
    sa.Column('total_detections', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint('birth_date IS NULL OR birth_date <= acquisition_date', name='check_birth_before_acquisition'),
    sa.CheckConstraint('total_detections >= 0', name='check_detections_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_last_detected_at'), 'animals', ['last_detected_at'], unique=False)
    op.create_index(op.f('ix_animals_species'), 'animals', ['species'], unique=False)
    op.create_index('ix_animals_species_status', 'animals', ['species', 'status'], unique=False)
    op.create_index(op.f('ix_animals_status'), 'animals', ['status'], unique=False)
    op.create_index('ix_animals_status_last_detected', 'animals', ['status', 'last_detected_at'], unique=False)
    op.create_index(op.f('ix_animals_tag_id'), 'animals', ['tag_id'], unique=True)
    op.create_table('adi_logs',
    sa.Column('animal_id', sa.Integer(), nullable=False, comment='Reference to the animal'),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when ADI was computed'),
    sa.Column('calculation_date', sa.String(length=10), nullable=False, comment='Date this ADI covers, ISO format YYYY-MM-DD'),
    sa.Column('adi_score', sa.Float(), nullable=False, comment='Final weighted ADI score (0.0 — 100.0)'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='healthy | average | warning | critical'),
    sa.Column('activity_score', sa.Float(), nullable=True, comment='Activity level from camera detections (weight: 0.20)'),
    sa.Column('feeding_score', sa.Float(), nullable=True, comment='Feeding behavior — visits to food area (weight: 0.20)'),
    sa.Column('drinking_score', sa.Float(), nullable=True, comment='Drinking behavior — visits to water area (weight: 0.10)'),
    sa.Column('movement_score', sa.Float(), nullable=True, comment='Movement quality — bbox velocity and pattern (weight: 0.15)'),
    sa.Column('growth_score', sa.Float(), nullable=True, comment='Growth dynamics — bbox size trend over 30 days (weight: 0.20)'),
    sa.Column('social_score', sa.Float(), nullable=True, comment='Social index — co-detections with other animals (weight: 0.10)'),
    sa.Column('sensor_score', sa.Float(), nullable=True, comment='IoT sensor data — temp, heart rate (weight: 0.05)'),
    sa.Column('veterinary_score', sa.Float(), nullable=True, comment='Veterinary status — checkups, vaccinations (weight: 0.05) — manual input'),
    sa.Column('data_quality', sa.Float(), nullable=False, comment='Fraction of components with real data (0.0—1.0). Low quality = fewer cameras / missing sensors.'),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='Full calculation detail for debugging and retraining. Contains per-component breakdowns, detection counts, bbox series, sensor readings, etc.'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='Auto-generated or manual observation note'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint("category IN ('healthy', 'average', 'warning', 'critical')", name='ck_adi_category_valid'),
    sa.CheckConstraint('adi_score >= 0.0 AND adi_score <= 100.0', name='ck_adi_score_range'),
    sa.CheckConstraint('data_quality >= 0.0 AND data_quality <= 1.0', name='ck_adi_data_quality_range'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id', 'calculation_date', name='uq_adi_log_animal_date')
    )
    op.create_index('ix_adi_logs_animal_date', 'adi_logs', ['animal_id', 'calculation_date'], unique=False)
    op.create_index(op.f('ix_adi_logs_animal_id'), 'adi_logs', ['animal_id'], unique=False)
    op.create_index(op.f('ix_adi_logs_category'), 'adi_logs', ['category'], unique=False)
    op.create_index('ix_adi_logs_category_date', 'adi_logs', ['category', 'calculation_date'], unique=False)
    op.create_index('ix_adi_logs_score_date', 'adi_logs', ['adi_score', 'calculation_date'], unique=False)
    op.create_table('alerts',
    sa.Column('animal_id', sa.Integer(), nullable=True, comment='Target animal. NULL for system-level alerts (e.g. camera offline)'),
    sa.Column('camera_id', sa.String(length=50), nullable=True, comment='Camera that triggered the alert, if applicable'),
    sa.Column('alert_type', sa.String(length=50), nullable=False, comment='Alert type identifier (AlertType enum value)'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='low | medium | high | critical'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='open | seen | resolved | dismissed'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Short human-readable title for UI display'),
    sa.Column('description', sa.Text(), nullable=False, comment='Full description with context and recommended action'),
    sa.Column('auto_generated', sa.Boolean(), nullable=False, comment='True = system generated, False = manually created'),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False, comment='When the alert condition was detected'),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True, comment='When a user first viewed this alert'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='When the alert was resolved or dismissed'),
    sa.Column('resolved_by', sa.String(length=100), nullable=True, comment='User/system that resolved the alert'),
    sa.Column('resolution_note', sa.Text(), nullable=True, comment='What action was taken to resolve'),
    sa.Column('context', sa.JSON(), nullable=True, comment='Alert-specific structured data. Schema varies by alert_type. Examples: ADI_SHARP_DROP → {prev_score, curr_score, drop_amount} ANIMAL_MISSING → {last_seen_at, hours_missing} HIGH_TEMPERATURE → {temperature, threshold, camera_id}'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_alert_severity_valid'),
    sa.CheckConstraint("status IN ('open', 'seen', 'resolved', 'dismissed')", name='ck_alert_status_valid'),
    sa.CheckConstraint('resolved_at IS NULL OR resolved_at >= triggered_at', name='ck_alert_resolved_after_triggered'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_animal_id'), 'alerts', ['animal_id'], unique=False)
    op.create_index('ix_alerts_animal_status', 'alerts', ['animal_id', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_severity', 'alerts', ['status', 'severity'], unique=False)
    op.create_index('ix_alerts_triggered_at', 'alerts', ['triggered_at'], unique=False)
    op.create_index('ix_alerts_type_status', 'alerts', ['alert_type', 'status'], unique=False)
    op.create_table('animal_embeddings',
    sa.Column('animal_id', sa.Integer(), nullable=False, comment='Animal this embedding belongs to'),
    sa.Column('embedding', sa.JSON(), nullable=False, comment='MobileNetV2 1280-dim L2-normalized embedding vector'),
    sa.Column('photo_path', sa.String(length=500), nullable=True, comment='Path to muzzle reference photo'),
    sa.Column('is_reference', sa.Boolean(), nullable=False, comment='True for the primary/best embedding shown in UI'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='How this embedding was created: registration | auto_detection'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='Quality score 0-1 based on detection confidence and image clarity'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_embeddings_animal_id'), 'animal_embeddings', ['animal_id'], unique=False)
    op.create_index(op.f('ix_animal_embeddings_is_reference'), 'animal_embeddings', ['is_reference'], unique=False)
    op.create_index('ix_embeddings_animal_reference', 'animal_embeddings', ['animal_id', 'is_reference'], unique=False)
    op.create_table('detections',
    sa.Column('animal_id', sa.Integer(), nullable=True, comment='Identified animal; NULL when animal could not be matched'),
    sa.Column('camera_id', sa.String(length=50), nullable=False, comment='Camera identifier'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of the captured frame'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='YOLO detection confidence (0.0–1.0)'),
    sa.Column('class_id', sa.Integer(), nullable=False, comment='COCO dataset class id'),
    sa.Column('class_name', sa.String(length=50), nullable=False, comment='Human-readable COCO class name'),
    sa.Column('bbox', sa.JSON(), nullable=False, comment='Normalised bounding box (cx, cy, w, h) in [0,1]'),
    sa.Column('estimated_weight', sa.Float(), nullable=True, comment='Weight estimate in kg (if calculated at detection time)'),
    sa.Column('frame_number', sa.Integer(), nullable=True, comment='Sequential frame number from the camera stream'),
    sa.Column('inference_time_ms', sa.Float(), nullable=True, comment='YOLO inference latency in milliseconds'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_detection_confidence_range'),
    sa.CheckConstraint('estimated_weight IS NULL OR estimated_weight > 0', name='ck_detection_weight_positive'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_animal_id'), 'detections', ['animal_id'], unique=False)
    op.create_index('ix_detections_animal_time', 'detections', ['animal_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_detections_camera_id'), 'detections', ['camera_id'], unique=False)
    op.create_index('ix_detections_camera_time', 'detections', ['camera_id', 'timestamp'], unique=False)
    op.create_index('ix_detections_class_time', 'detections', ['class_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_detections_timestamp'), 'detections', ['timestamp'], unique=False)
    op.create_table('health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.Enum('CHECKUP', 'TREATMENT', 'VACCINATION', 'INJURY', 'SURGERY', 'ILLNESS', 'OTHER', name='healthrecordtype'), nullable=False, comment='Type of health record'),
    sa.Column('severity', sa.Enum('NORMAL', 'WARNING', 'CRITICAL', name='healthrecordseverity'), nullable=False, comment='Severity level'),
    sa.Column('diagnosis', sa.String(length=500), nullable=False, comment='Medical diagnosis or condition'),
    sa.Column('symptoms', sa.Text(), nullable=True, comment='Observed symptoms'),
    sa.Column('treatment', sa.Text(), nullable=True, comment='Treatment provided'),
    sa.Column('medication', sa.String(length=300), nullable=True, comment='Medications administered'),
    sa.Column('dosage', sa.String(length=100), nullable=True, comment='Medication dosage'),
    sa.Column('veterinarian', sa.String(length=200), nullable=True, comment='Veterinarian name'),
    sa.Column('clinic_name', sa.String(length=300), nullable=True, comment='Clinic or hospital name'),
    sa.Column('cost', sa.Float(), nullable=True, comment='Cost of treatment'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('recorded_at', sa.DateTime(), nullable=False, comment='Date/time of record'),
    sa.Column('next_checkup_date', sa.Date(), nullable=True, comment='Date of next scheduled checkup'),
    sa.Column('is_resolved', sa.Boolean(), nullable=False, comment='Whether the issue is resolved'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='Date/time when resolved'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record update timestamp'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_records_animal_id'), 'health_records', ['animal_id'], unique=False)
    op.create_index(op.f('ix_health_records_id'), 'health_records', ['id'], unique=False)
    op.create_index(op.f('ix_health_records_is_resolved'), 'health_records', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_health_records_next_checkup_date'), 'health_records', ['next_checkup_date'], unique=False)
    op.create_index(op.f('ix_health_records_record_type'), 'health_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_health_records_recorded_at'), 'health_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_health_records_severity'), 'health_records', ['severity'], unique=False)
    op.create_table('weight_measurements',
    sa.Column('animal_id', sa.Integer(), nullable=False, comment='Reference to the animal being measured'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='When the measurement was captured (camera timestamp)'),
    sa.Column('estimated_weight_kg', sa.Float(), nullable=False, comment='AI-estimated weight in kilograms'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='AI model confidence score (0.0 to 1.0)'),
    sa.Column('camera_id', sa.String(length=50), nullable=False, comment='Identifier of the camera that captured this measurement'),
    sa.Column('raw_ai_data', sa.JSON(), nullable=True, comment='\n        Raw AI model output stored as JSONB. May include:\n        - bounding_box: {x, y, width, height}\n        - segmentation_mask: compressed polygon coordinates\n        - feature_vector: embedding from neural network\n        - model_version: version of the AI model used\n        - processing_time_ms: inference latency\n        \n        This data is crucial for:\n        1. Model retraining (ground truth comparison)\n        2. Debugging incorrect predictions\n        3. A/B testing different model versions\n        4. Performance monitoring\n        '),
    sa.Column('image_path', sa.String(length=500), nullable=True, comment='Path to stored image frame (if enabled)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='check_confidence_range'),
    sa.CheckConstraint('estimated_weight_kg > 0', name='check_weight_positive'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_measurements_animal_id'), 'weight_measurements', ['animal_id'], unique=False)
    op.create_index('ix_weight_measurements_animal_time', 'weight_measurements', ['animal_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_weight_measurements_camera_id'), 'weight_measurements', ['camera_id'], unique=False)
    op.create_index('ix_weight_measurements_camera_time', 'weight_measurements', ['camera_id', 'timestamp'], unique=False)
    op.create_index('ix_weight_measurements_confidence', 'weight_measurements', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_weight_measurements_confidence_score'), 'weight_measurements', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_weight_measurements_timestamp'), 'weight_measurements', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_measurements_timestamp'), table_name='weight_measurements')
    op.drop_index(op.f('ix_weight_measurements_confidence_score'), table_name='weight_measurements')
    op.drop_index('ix_weight_measurements_confidence', table_name='weight_measurements')
    op.drop_index('ix_weight_measurements_camera_time', table_name='weight_measurements')
    op.drop_index(op.f('ix_weight_measurements_camera_id'), table_name='weight_measurements')
    op.drop_index('ix_weight_measurements_animal_time', table_name='weight_measurements')
    op.drop_index(op.f('ix_weight_measurements_animal_id'), table_name='weight_measurements')
    op.drop_table('weight_measurements')
    op.drop_index(op.f('ix_health_records_severity'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_recorded_at'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_record_type'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_next_checkup_date'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_is_resolved'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_id'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_animal_id'), table_name='health_records')
    op.drop_table('health_records')
    op.drop_index(op.f('ix_detections_timestamp'), table_name='detections')
    op.drop_index('ix_detections_class_time', table_name='detections')
    op.drop_index('ix_detections_camera_time', table_name='detections')
    op.drop_index(op.f('ix_detections_camera_id'), table_name='detections')
    op.drop_index('ix_detections_animal_time', table_name='detections')
    op.drop_index(op.f('ix_detections_animal_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index('ix_embeddings_animal_reference', table_name='animal_embeddings')
    op.drop_index(op.f('ix_animal_embeddings_is_reference'), table_name='animal_embeddings')
    op.drop_index(op.f('ix_animal_embeddings_animal_id'), table_name='animal_embeddings')
    op.drop_table('animal_embeddings')
    op.drop_index('ix_alerts_type_status', table_name='alerts')
    op.drop_index('ix_alerts_triggered_at', table_name='alerts')
    op.drop_index('ix_alerts_status_severity', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index('ix_alerts_animal_status', table_name='alerts')
    op.drop_index(op.f('ix_alerts_animal_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_adi_logs_score_date', table_name='adi_logs')
    op.drop_index('ix_adi_logs_category_date', table_name='adi_logs')
    op.drop_index(op.f('ix_adi_logs_category'), table_name='adi_logs')
    op.drop_index(op.f('ix_adi_logs_animal_id'), table_name='adi_logs')
    op.drop_index('ix_adi_logs_animal_date', table_name='adi_logs')
    op.drop_table('adi_logs')
    op.drop_index(op.f('ix_animals_tag_id'), table_name='animals')
    op.drop_index('ix_animals_status_last_detected', table_name='animals')
    op.drop_index(op.f('ix_animals_status'), table_name='animals')
    op.drop_index('ix_animals_species_status', table_name='animals')
    op.drop_index(op.f('ix_animals_species'), table_name='animals')
    op.drop_index(op.f('ix_animals_last_detected_at'), table_name='animals')
    op.drop_table('animals')
    # ### end Alembic commands ###
