"""add_users_table

Revision ID: a2e5c73483c5
Revises: 50e524a6cb38
Create Date: 2026-02-21 15:37:46.965569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e5c73483c5'
down_revision: Union[str, None] = '50e524a6cb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email manzili — login uchun ishlatiladi'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Noyob foydalanuvchi nomi (lotin harflari, raqamlar, _)'),
    sa.Column('full_name', sa.String(length=150), nullable=True, comment="To'liq ism — ko'rsatish uchun"),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt hash — plain text hech qachon saqlanmaydi'),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=True, comment="SHA-256(refresh_token) — logout qilganda NULL ga o'rnatiladi"),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'VIEWER', name='user_role'), nullable=False, comment='Foydalanuvchi roli: admin | manager | viewer'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment="False = foydalanuvchi bloklangan (o'chirilmaydi, faqat deaktivlanadi)"),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Oxirgi muvaffaqiyatli login vaqti (UTC)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
