"""Initial migration: create animals table

Revision ID: d7736d55a532
Revises: 
Create Date: 2026-02-10 15:03:36.299931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7736d55a532'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('tag_id', sa.String(length=50), nullable=False, comment='Unique tag identifier (e.g., JNV-001)'),
    sa.Column('species', sa.Enum('CATTLE', 'SHEEP', 'GOAT', 'HORSE', 'OTHER', name='animal_species'), nullable=False, comment='Species type'),
    sa.Column('breed', sa.String(length=100), nullable=True, comment='Specific breed name'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='animal_gender'), nullable=False, comment='Gender classification'),
    sa.Column('birth_date', sa.DateTime(), nullable=True, comment='Date of birth (if known)'),
    sa.Column('acquisition_date', sa.DateTime(), nullable=False, comment='Date when animal was acquired/added to farm'),
    sa.Column('status', sa.Enum('ACTIVE', 'QUARANTINE', 'SICK', 'SOLD', 'DECEASED', 'TRANSFERRED', name='animal_status'), nullable=False, comment='Current lifecycle status'),
    sa.Column('first_detected_at', sa.DateTime(), nullable=True, comment='First time detected by camera system'),
    sa.Column('last_detected_at', sa.DateTime(), nullable=True, comment='Most recent detection timestamp'),
    sa.Column('total_detections', sa.Integer(), nullable=False, comment='Total number of times detected'),
    sa.Column('notes', sa.String(length=1000), nullable=True, comment='Additional notes or observations'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.CheckConstraint('birth_date IS NULL OR birth_date <= acquisition_date', name='check_birth_before_acquisition'),
    sa.CheckConstraint('total_detections >= 0', name='check_detections_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_last_detected_at'), 'animals', ['last_detected_at'], unique=False)
    op.create_index(op.f('ix_animals_species'), 'animals', ['species'], unique=False)
    op.create_index('ix_animals_species_status', 'animals', ['species', 'status'], unique=False)
    op.create_index(op.f('ix_animals_status'), 'animals', ['status'], unique=False)
    op.create_index('ix_animals_status_last_detected', 'animals', ['status', 'last_detected_at'], unique=False)
    op.create_index(op.f('ix_animals_tag_id'), 'animals', ['tag_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animals_tag_id'), table_name='animals')
    op.drop_index('ix_animals_status_last_detected', table_name='animals')
    op.drop_index(op.f('ix_animals_status'), table_name='animals')
    op.drop_index('ix_animals_species_status', table_name='animals')
    op.drop_index(op.f('ix_animals_species'), table_name='animals')
    op.drop_index(op.f('ix_animals_last_detected_at'), table_name='animals')
    op.drop_table('animals')
    # ### end Alembic commands ###
